Functionality Redesign
gustavwilliam/bestpy pull request #15
Opened 2020-12-12 03:52 UTC by SuperMaZingCoder

Removed lots of code; instead, it creates a class and whenever you pull an attribute from it, the class looks at the answers file and responds accordingly. 

```py
from .answers import answers

import random

class Best:
    def __getattribute__(self, name):
        # Return random value in list
        if type(answers[name]) != list:
            return answers[name]
        else:
            return random.choice(answers[name])
```

2020-12-12 10:06 UTC, vivax3794 commented on bestpy/best.py
> +            return random.choice(answers[name])
using isinstance and swapping around the if and else makes more sense here.

```suggestion
        if isinstance(answers[name], list):
            return random.choice(answers[name])
        else:
            return answers[name]
```

2020-12-12 20:57 UTC, gustavwilliam commented
@SuperMaZingCoder Thanks for the PR. After the newly merged PR to add pre-commit and reformat some of the code, this can't currently be merged. Would you like to have a look at how the conflicts could be resolved?

2020-12-12 20:59 UTC, SuperMaZingCoder commented
I'd be happy to. I'm currently not available, but I will look at it once I am \:D

2020-12-12 21:27 UTC, gustavwilliam commented
Alright! Thanks a lot.

2020-12-14 22:42 UTC, SuperMaZingCoder commented
@gustavwilliam All conflicts are resolved. Let me know if I need to do anything else with the PR, otherwise, merge it and let me know (here or in discord).

2020-12-15 06:57 UTC, gustavwilliam reviewed
Overall, nice change! It fixes some of the issues we had with the previous version, such as not being able to use the package at all (a... major issue).

2020-12-15 06:57 UTC, gustavwilliam commented on bestpy/answers.py
> -        return name
Did this completely vanish? Any reason for that? I think the variable inputs, that change depending on the user, are quite fun to have.

2020-12-15 20:10 UTC, gustavwilliam requested changes
Overall, "I'm lovin' it". Just one comment.

2020-12-15 20:10 UTC, gustavwilliam commented on bestpy/best.py
> +            return answers[name]
```suggestion
    def __getattribute__(self, name):
        answer = answers[name]
        if callable(answer):
            answer = answer()
            
        if isinstance(answer, list):
            return random.choice(answer)
        else:
            return answer
```
Sometimes, the functions may return lists. We should expect the return values to act the same way that we expect the answers to act, if that makes sense. Calling it — if it's a function — could help provide the return value and let us continue parsing it as usual. This currently also looks slightly messy in my opinion.

2020-12-15 20:20 UTC, merged